//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.LocationSampleDataSource
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class LocationSampleDataSource { }
#else

	public class LocationSampleDataSource : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public LocationSampleDataSource()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/MyTravelHistory;component/SampleData/LocationSampleDataSource/LocationSampleDataSource.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private AllLocations _AllLocations = new AllLocations();

		public AllLocations AllLocations
		{
			get
			{
				return this._AllLocations;
			}
		}
	}

	public class AllLocations : System.Collections.ObjectModel.ObservableCollection<AllLocationsItem>
	{ 
	}

	public class AllLocationsItem : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _Name = string.Empty;

		public string Name
		{
			get
			{
				return this._Name;
			}

			set
			{
				if (this._Name != value)
				{
					this._Name = value;
					this.OnPropertyChanged("Name");
				}
			}
		}

		private string _Latitude = string.Empty;

		public string Latitude
		{
			get
			{
				return this._Latitude;
			}

			set
			{
				if (this._Latitude != value)
				{
					this._Latitude = value;
					this.OnPropertyChanged("Latitude");
				}
			}
		}

		private string _Longtitude = string.Empty;

		public string Longtitude
		{
			get
			{
				return this._Longtitude;
			}

			set
			{
				if (this._Longtitude != value)
				{
					this._Longtitude = value;
					this.OnPropertyChanged("Longtitude");
				}
			}
		}

		private Address _Address = new Address();

		public Address Address
		{
			get
			{
				return this._Address;
			}
		}
	}

	public class AddressItem : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _Street = string.Empty;

		public string Street
		{
			get
			{
				return this._Street;
			}

			set
			{
				if (this._Street != value)
				{
					this._Street = value;
					this.OnPropertyChanged("Street");
				}
			}
		}

		private double _HouseNumber = 0;

		public double HouseNumber
		{
			get
			{
				return this._HouseNumber;
			}

			set
			{
				if (this._HouseNumber != value)
				{
					this._HouseNumber = value;
					this.OnPropertyChanged("HouseNumber");
				}
			}
		}

		private double _PostalCode = 0;

		public double PostalCode
		{
			get
			{
				return this._PostalCode;
			}

			set
			{
				if (this._PostalCode != value)
				{
					this._PostalCode = value;
					this.OnPropertyChanged("PostalCode");
				}
			}
		}

		private string _City = string.Empty;

		public string City
		{
			get
			{
				return this._City;
			}

			set
			{
				if (this._City != value)
				{
					this._City = value;
					this.OnPropertyChanged("City");
				}
			}
		}

		private string _District = string.Empty;

		public string District
		{
			get
			{
				return this._District;
			}

			set
			{
				if (this._District != value)
				{
					this._District = value;
					this.OnPropertyChanged("District");
				}
			}
		}

		private string _State = string.Empty;

		public string State
		{
			get
			{
				return this._State;
			}

			set
			{
				if (this._State != value)
				{
					this._State = value;
					this.OnPropertyChanged("State");
				}
			}
		}
	}

	public class Address : System.Collections.ObjectModel.ObservableCollection<AddressItem>
	{ 
	}
#endif
}
