//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.LocationSampleDataSource
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class LocationSampleDataSource { }
#else

	public class LocationSampleDataSource : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public LocationSampleDataSource()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/MyTravelHistory;component/SampleData/LocationSampleDataSource/LocationSampleDataSource.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private AllLocations _AllLocations = new AllLocations();

		public AllLocations AllLocations
		{
			get
			{
				return this._AllLocations;
			}
		}
	}

	public class AllLocationsItem : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _Name = string.Empty;

		public string Name
		{
			get
			{
				return this._Name;
			}

			set
			{
				if (this._Name != value)
				{
					this._Name = value;
					this.OnPropertyChanged("Name");
				}
			}
		}

		private string _Latitude = string.Empty;

		public string Latitude
		{
			get
			{
				return this._Latitude;
			}

			set
			{
				if (this._Latitude != value)
				{
					this._Latitude = value;
					this.OnPropertyChanged("Latitude");
				}
			}
		}

		private string _Longtitude = string.Empty;

		public string Longtitude
		{
			get
			{
				return this._Longtitude;
			}

			set
			{
				if (this._Longtitude != value)
				{
					this._Longtitude = value;
					this.OnPropertyChanged("Longtitude");
				}
			}
		}
	}

	public class AllLocations : System.Collections.ObjectModel.ObservableCollection<AllLocationsItem>
	{ 
	}
#endif
}
