//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTravelHistory.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyTravelHistory.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutLabel {
            get {
                return ResourceManager.GetString("AboutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accuracy: .
        /// </summary>
        public static string AccuracyLabel {
            get {
                return ResourceManager.GetString("AccuracyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add image.
        /// </summary>
        public static string AddImageLabel {
            get {
                return ResourceManager.GetString("AddImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AddLabel {
            get {
                return ResourceManager.GetString("AddLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to address.
        /// </summary>
        public static string AddressLabel {
            get {
                return ResourceManager.GetString("AddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add tag.
        /// </summary>
        public static string AddTag {
            get {
                return ResourceManager.GetString("AddTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Name of your tag:.
        /// </summary>
        public static string AddTagMessage {
            get {
                return ResourceManager.GetString("AddTagMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AddTitle {
            get {
                return ResourceManager.GetString("AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Travel History.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your backup was created succesfully!.
        /// </summary>
        public static string BackupCreatedMessage {
            get {
                return ResourceManager.GetString("BackupCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to backup / restore.
        /// </summary>
        public static string BackupLabel {
            get {
                return ResourceManager.GetString("BackupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to backup / restore.
        /// </summary>
        public static string BackupTitle {
            get {
                return ResourceManager.GetString("BackupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bar.
        /// </summary>
        public static string BarLabel {
            get {
                return ResourceManager.GetString("BarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string CancelLabel {
            get {
                return ResourceManager.GetString("CancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to changelog:.
        /// </summary>
        public static string ChangelogLabel {
            get {
                return ResourceManager.GetString("ChangelogLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Init.
        /// </summary>
        public static string ChangelogText {
            get {
                return ResourceManager.GetString("ChangelogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comment.
        /// </summary>
        public static string CommentLabel {
            get {
                return ResourceManager.GetString("CommentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wanna restore your backup? Your current data will be overwritten.
        /// </summary>
        public static string ConfirmRestoreBackupMessage {
            get {
                return ResourceManager.GetString("ConfirmRestoreBackupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Backup?.
        /// </summary>
        public static string ConfirmRestoreBackupMessageTitle {
            get {
                return ResourceManager.GetString("ConfirmRestoreBackupMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create backup.
        /// </summary>
        public static string CreateBackupLabel {
            get {
                return ResourceManager.GetString("CreateBackupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your current position.
        /// </summary>
        public static string CurrentPositionLabel {
            get {
                return ResourceManager.GetString("CurrentPositionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string DeleteLabel {
            get {
                return ResourceManager.GetString("DeleteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this location?.
        /// </summary>
        public static string DeleteMessageLocation {
            get {
                return ResourceManager.GetString("DeleteMessageLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this tags?.
        /// </summary>
        public static string DeleteMessageTag {
            get {
                return ResourceManager.GetString("DeleteMessageTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete?.
        /// </summary>
        public static string DeleteMessageTitle {
            get {
                return ResourceManager.GetString("DeleteMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to details.
        /// </summary>
        public static string DetailsTitle {
            get {
                return ResourceManager.GetString("DetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to developer:.
        /// </summary>
        public static string DeveloperLabel {
            get {
                return ResourceManager.GetString("DeveloperLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        public static string DoneLabel {
            get {
                return ResourceManager.GetString("DoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        public static string DoneMessageTitle {
            get {
                return ResourceManager.GetString("DoneMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string EditLabel {
            get {
                return ResourceManager.GetString("EditLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string EditTitle {
            get {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there went something Wrong..
        /// </summary>
        public static string GeneralErrorMessage {
            get {
                return ResourceManager.GetString("GeneralErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops....
        /// </summary>
        public static string GeneralErrorMessageTitle {
            get {
                return ResourceManager.GetString("GeneralErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting your position....
        /// </summary>
        public static string GettingYourPositionLabel {
            get {
                return ResourceManager.GetString("GettingYourPositionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hotel.
        /// </summary>
        public static string HotelLabel {
            get {
                return ResourceManager.GetString("HotelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your last backup was created at: .
        /// </summary>
        public static string LastBackupLabel {
            get {
                return ResourceManager.GetString("LastBackupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to load backup.
        /// </summary>
        public static string LoadBackupLabel {
            get {
                return ResourceManager.GetString("LoadBackupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location.
        /// </summary>
        public static string LocationLabel {
            get {
                return ResourceManager.GetString("LocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all locations.
        /// </summary>
        public static string LocationsTitle {
            get {
                return ResourceManager.GetString("LocationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location.
        /// </summary>
        public static string LocationTitle {
            get {
                return ResourceManager.GetString("LocationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to museum.
        /// </summary>
        public static string MuseumLabel {
            get {
                return ResourceManager.GetString("MuseumLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to navigate.
        /// </summary>
        public static string NavigateLabel {
            get {
                return ResourceManager.GetString("NavigateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [empty name].
        /// </summary>
        public static string NoNameDefaultEntry {
            get {
                return ResourceManager.GetString("NoNameDefaultEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We still trying to fetch get your current position. Please wait a second before you save your entry..
        /// </summary>
        public static string NoPositionMessage {
            get {
                return ResourceManager.GetString("NoPositionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown position!.
        /// </summary>
        public static string NoPositionMessageTitle {
            get {
                return ResourceManager.GetString("NoPositionMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you continue the existing backup on skydrive will be overwritten.
        ///Do you wanna proceed?.
        /// </summary>
        public static string OverwriteBackupMessage {
            get {
                return ResourceManager.GetString("OverwriteBackupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite backup?.
        /// </summary>
        public static string OverwriteBackupTitle {
            get {
                return ResourceManager.GetString("OverwriteBackupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin to start.
        /// </summary>
        public static string PintToStartLabel {
            get {
                return ResourceManager.GetString("PintToStartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be logged in to backup or restore your data..
        /// </summary>
        public static string PleaseLogInText {
            get {
                return ResourceManager.GetString("PleaseLogInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate MyTravelHistory!.
        /// </summary>
        public static string RateAppLabel {
            get {
                return ResourceManager.GetString("RateAppLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message of the developer:.
        /// </summary>
        public static string ReleaseMessageLabel {
            get {
                return ResourceManager.GetString("ReleaseMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you like this App please rate it in the Marketplace!
        ///I&apos;m looking forward to receive your feedback! =).
        /// </summary>
        public static string ReleaseMessageText {
            get {
                return ResourceManager.GetString("ReleaseMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restaurant.
        /// </summary>
        public static string RestaurantLabel {
            get {
                return ResourceManager.GetString("RestaurantLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restore backup.
        /// </summary>
        public static string RestoreBackupLabel {
            get {
                return ResourceManager.GetString("RestoreBackupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup successful restored! I will take you to your MainPage..
        /// </summary>
        public static string RestoreCompletedMessage {
            get {
                return ResourceManager.GetString("RestoreCompletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restore.
        /// </summary>
        public static string RestoreTitle {
            get {
                return ResourceManager.GetString("RestoreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select.
        /// </summary>
        public static string SelectLabel {
            get {
                return ResourceManager.GetString("SelectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsLabel {
            get {
                return ResourceManager.GetString("SettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share.
        /// </summary>
        public static string ShareLabel {
            get {
                return ResourceManager.GetString("ShareLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shop.
        /// </summary>
        public static string ShopLabel {
            get {
                return ResourceManager.GetString("ShopLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show all on Map.
        /// </summary>
        public static string ShowAllOnMapLabel {
            get {
                return ResourceManager.GetString("ShowAllOnMapLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support address:.
        /// </summary>
        public static string SupportAddressLabel {
            get {
                return ResourceManager.GetString("SupportAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nino.padrutt@hotmail.com.
        /// </summary>
        public static string SupportAddressMail {
            get {
                return ResourceManager.GetString("SupportAddressMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage Tags.
        /// </summary>
        public static string TagLabel {
            get {
                return ResourceManager.GetString("TagLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tags.
        /// </summary>
        public static string TagTitle {
            get {
                return ResourceManager.GetString("TagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process to create the backup got cancelled. Please be sure that have a good internet connection and try it again..
        /// </summary>
        public static string TaskCancelledErrorMessage {
            get {
                return ResourceManager.GetString("TaskCancelledErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Backup cancelled.
        /// </summary>
        public static string TaskCancelledErrorTitle {
            get {
                return ResourceManager.GetString("TaskCancelledErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version:.
        /// </summary>
        public static string VersionLabel {
            get {
                return ResourceManager.GetString("VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to viewpoint.
        /// </summary>
        public static string ViewpointLabel {
            get {
                return ResourceManager.GetString("ViewpointLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to what&apos;s new?.
        /// </summary>
        public static string WhatsNewTitle {
            get {
                return ResourceManager.GetString("WhatsNewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to work.
        /// </summary>
        public static string WorkLabel {
            get {
                return ResourceManager.GetString("WorkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you are here.
        /// </summary>
        public static string YouAreHereText {
            get {
                return ResourceManager.GetString("YouAreHereText", resourceCulture);
            }
        }
    }
}
